// Generated by: dart run tool/generate_firebase_options.dart
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members

import 'dart:io' show Platform;

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (Platform.isAndroid) return android;
    if (Platform.isIOS) return ios;
    return android;
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDvJdPfojtdRbB1KdY9RwOt1Zxy1j7xLbM',
    appId: '1:736452239702:android:213c0e8b9980858bd7b6f7',
    messagingSenderId: '736452239702',
    projectId: 'e-baby-81746',
    storageBucket: 'e-baby-81746.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDvJdPfojtdRbB1KdY9RwOt1Zxy1j7xLbM',
    appId: '1:736452239702:android:213c0e8b9980858bd7b6f7',
    messagingSenderId: '736452239702',
    projectId: 'e-baby-81746',
    storageBucket: 'e-baby-81746.firebasestorage.app',
    iosBundleId: 'com.example.e_baby_flutter',
  );
}
