/// Run from project root: dart run tool/generate_firebase_options.dart
/// Requires: android/app/google-services.json (download from Firebase Console
/// → E-Baby project → Project settings → Your apps → Android app).

import 'dart:convert';
import 'dart:io';

void main() {
  final projectRoot = Directory.current;
  if (!projectRoot.path.endsWith('e_baby_flutter')) {
    print('Run from e_baby_flutter folder: dart run tool/generate_firebase_options.dart');
    exit(1);
  }
  final gsPath = projectRoot.path + '/android/app/google-services.json';
  final file = File(gsPath);
  if (!file.existsSync()) {
    print('Missing: android/app/google-services.json');
    print('1. Firebase Console → E-Baby → Project settings → General');
    print('2. Your apps → Add app → Android');
    print('3. Package: com.example.e_baby_flutter');
    print('4. Download google-services.json and put it in android/app/');
    exit(1);
  }
  final map = jsonDecode(file.readAsStringSync()) as Map<String, dynamic>;
  final projectInfo = map['project_info'] as Map<String, dynamic>?;
  final clients = map['client'] as List<dynamic>?;
  if (projectInfo == null || clients == null || clients.isEmpty) {
    print('Invalid google-services.json structure');
    exit(1);
  }
  final client = clients.first as Map<String, dynamic>;
  final apiKey = (client['api_key'] as List<dynamic>?)?.firstOrNull;
  final currentKey = apiKey is Map ? apiKey['current_key'] as String? : null;
  final clientInfo = client['client_info'] as Map<String, dynamic>?;
  final appId = clientInfo?['mobilesdk_app_id'] as String?;
  final projectNumber = projectInfo['project_number'] as String?;
  final projectId = projectInfo['project_id'] as String? ?? 'e-baby-81746';
  final storageBucket = projectInfo['storage_bucket'] as String? ?? '$projectId.appspot.com';

  if (currentKey == null || appId == null || projectNumber == null) {
    print('Could not read api_key, app_id, or project_number from google-services.json');
    exit(1);
  }

  final outPath = projectRoot.path + '/lib/firebase_options.dart';
  final content = '''
// Generated by: dart run tool/generate_firebase_options.dart
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members

import 'dart:io' show Platform;

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (Platform.isAndroid) return android;
    if (Platform.isIOS) return ios;
    return android;
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: '$currentKey',
    appId: '$appId',
    messagingSenderId: '$projectNumber',
    projectId: '$projectId',
    storageBucket: '$storageBucket',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: '$currentKey',
    appId: '$appId',
    messagingSenderId: '$projectNumber',
    projectId: '$projectId',
    storageBucket: '$storageBucket',
    iosBundleId: 'com.example.e_baby_flutter',
  );
}
''';
  File(outPath).writeAsStringSync(content);
  print('Updated lib/firebase_options.dart from google-services.json');
}

extension on List<dynamic> {
  dynamic get firstOrNull => isEmpty ? null : first;
}